@startuml
cell_search_proc -> phy_controller:start_cell_search
participant phy
participant sync
activate phy_controller
    phy_controller x->phy:cell_search
    activate phy
        phy->sync:scell_sync_stop
        activate sync
            note over sync
                <size:10> 这里没有重点看, 强制停止一些任务
            end note
            sync --> phy
        deactivate sync
        ''' TODO: 需要补充stop的事情
        phy->sync:cell_search_init
        activate sync
            sync -> sync_state:go_idle
            activate sync_state
            sync_state-->sync
            deactivate sync_state
            note over sync
                <size:10> next_state=IDLE
                <size:10> meas_stop()暂时没看
                <size:10> rrc_proc_state
                <size:10>   =PROC_SEARCH_START
            end note
            sync-->phy:true
        deactivate sync
    phy -->x phy_controller:?

    phy->phy_cmd_proc:add_cmd
    activate phy_cmd_proc
        note over phy_cmd_proc
            <size:10> lambda函数放进cmd_queue
        end note

    phy_cmd_proc-->phy
    deactivate phy_cmd_proc
    deactivate phy
phy_controller-->cell_search_proc:return false
deactivate phy_controller

'''
note over phy_cmd_proc
    <size:10> run_thread会自动取出
    <size:10> cmd_queue中的任务并运行
end note

phy_cmd_proc->phy_cmd_proc:run_thread
activate phy_cmd_proc
phy_cmd_proc -> sync:wait_idle
    activate sync
        sync->sync_state:wait_idle
        activate sync_state
            note over sync_state
                <size:10> 这里似乎是会阻塞, 等待
                <size:10> cur_state为IDLE时返
                <size:10> 回, 超过2000ms也返回
            end note

            sync_state-->sync:return true
        deactivate sync_state

        sync-->phy_cmd_proc:return
    deactivate sync

    phy_cmd_proc->phy:reset (暂时没看,)
    activate phy
        phy-->phy_cmd_proc
    deactivate phy
    phy_cmd_proc->sync:cell_search_start
    activate sync
        note over sync
            <size:10> rrc_proc_state=PROC_SEARCH_RUNNING
            <size:10> 设置srate为1.92e6
            <size:10> current_earfcn=3350
            <size:10> 调用set_frequency()设置dl/ul频率并且
            <size:10> 调用srsran_ue_sync_reset
        end note
        sync->sync_state:run_cell_search
        activate sync_state
            note over sync_state
                <size:10> go_state(CELL_SEARCH)设置next_state(这里要展开notify)
                <size:10>
            end note
            sync_state-->sync
        deactivate sync_state
        sync --> phy_cmd_proc:return cell_search_ret_t
    deactivate sync
deactivate phy_cmd_proc




@enduml